# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: checkout our repo
        uses: actions/checkout@v1

      - name: creating docker containers
        working-directory: ./server
        run: docker compose -f docker-compose.ci.yml up -d

      - name: running test inside node-app
        working-directory: ./server
        run: docker exec -t -e NODE_ENV=test -w /backend-app node-app npm run test:app
